### ISSUE TITLE
`DataMember::read` is unsound

### ISSUE THREAD

**Issue by SquareMan** [Tommoa/rs-process-memory#10]
Admittedly I'm not sure if this crate is still maintained but I'm not aware of any good alternatives.

Something I've recently come across is that it appears that the `DataMember::read` function is unsound. Since the only restrictions on `T` is that it is `Sized + Copy`, it is possible that [casting the buffer pointer to](https://github.com/Tommoa/rs-process-memory/blob/master/src/data_member.rs#L92) `*const T` and subsequent reading of it may be undefined behavior if the bit pattern contained in the buffer doesn't correspond to a valid `T`. This most clearly a potential issue when reading a `bool` which can only be 0 or 1, but could also be an issue for an enum.

**Comment by Tommoa** [comment]
Hi there, thanks for reporting this.

First of all, this crate _is_ maintained, but I consider it pretty much feature complete.
Of the other two open bugs, one has turned into a feature request from a misunderstanding of the API (which is partially handled by [other crates](https://docs.rs/dll-syringe/latest/dll_syringe/index.html) and the PRs for them seem to have fallen by the wayside) and the other I have been unable to reproduce myself and so can't do anything with for now. I'm also looking into how the eventual move to [strict provenance](https://doc.rust-lang.org/std/ptr/index.html#strict-provenance) for pointers may affect this crate, but don't have any immediate plans for changes.

With regards to the issue of soundness - I think this is intractable and have no idea how to solve it. If you have any suggestions, then I would welcome them and be happy to implement them.
The main issue here stems from the fact that we do not control the memory from which we are reading from, and thus - as far as I am aware - there is no way before reading the pointer that we can guarantee that the memory referred to is indeed a valid `T`.
With that in mind, would be best way to solve this be to either (non-exclusively):
- Flag the potential unsoundness for library consumers to have to deal with in documentation?
- Mark the function as unsafe? This again pushes the contract for safety to library consumers
- Some other option that I haven't thought about?

Thanks again for the report.

**Comment by SquareMan** [comment]
I am also unsure how the issue would best be fixed but I've been thinking of some ideas. At a minimum I think the function should be marked unsafe with the problem clearly laid out.

The only way that I can think of to truly fix this is to somehow inspect the buffer after copying the memory to make sure it contains a valid bit-pattern. I think this would probably require a trait to be added for this and implemented for the various types. Unfortunately this would probably be pretty messy. Due to coherence rules user's wouldn't be able to implement the trait for any types they don't own which could be a problem if the type you're interested in comes from a third crate.

I can provide some mockups later today and will continue thinking about the issue for a better preposal.

**Comment by SquareMan** [comment]
One solution might be to use [bytemuck](https://docs.rs/bytemuck/latest/bytemuck/checked/trait.CheckedBitPattern.html) to provide the traits and then use `CheckedBitPattern` as a trait bound for the read operation. Bytemuck can also handle the casting part as well. Only potetial downside I see to this (other than adding a dependency) is that it enforces Rust's requirements for reading a bool, which is good to avoid an invalid cast, but might not be what you want when reading an arbitrary external process's memory. This could be worked around though with some sort of inbetween type `T` that implements `From<T> for bool` though that treats all non-zero values as true.
